identifier: l8l5d1n3q6s16dy1
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: C:\Users\Multilent-PC\Desktop\my-angular\my-blog
distFolder: dist/my-blog
outDir: C:\Users\Multilent-PC\Desktop\my-angular\my-blog\dist\static
handle404: ''
allowErrorCollect: false
